# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage'
        mock.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/mocks'
        proxy.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/proxy'
