version: "3.9"

services:
  php:
    image: wodby/php:${PHP_TAG}
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      PHP_XDEBUG: 1
      PHP_XDEBUG_MODE: debug
      PHP_IDE_CONFIG: "serverName={PROJECT_BASE_URL}"
      PHP_XDEBUG_IDEKEY: $PHP_XDEBUG_IDEKEY
      PHP_XDEBUG_CLIENT_HOST: $PHP_XDEBUG_CLIENT_HOST
      PHP_XDEBUG_LOG: /var/www/html/var/log/php-xdebug.log
    volumes:
    - ./:/var/www/html
  nginx:
    image: wodby/nginx:${NGINX_TAG}
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
    - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_VHOST_PRESET: php
      NGINX_SERVER_ROOT: /var/www/html/public
    volumes:
    - ./:/var/www/html
    labels:
    - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"

  hub:
    image: irmpdz/api-proxy-mock:latest
    container_name: "${PROJECT_NAME}_hub"
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_hub.rule=Host(`hub.${PROJECT_BASE_URL}`)"

  traefik:
    image: traefik:${TRAEFIK_TAG}
    container_name: "${PROJECT_NAME}_traefik"
    command: --api.insecure=true --providers.docker
    ports:
    - '${TRAEFIK_HTTP_PORT}:80'
    - '8080:8080'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
