homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
      path: /admin
      permanent: true

admin.dashboard:
  path: /admin
  controller: App\Controller\Admin\DashboardController::display
  methods: GET|HEAD
  defaults:

admin.origin.list:
  path: /admin/origin
  controller: App\Controller\Admin\OriginController::list
  methods: GET|HEAD
admin.origin.add:
  path: /admin/origin/add
  controller: App\Controller\Admin\OriginController::add
  methods: GET|HEAD|POST
admin.origin.edit:
  path: /admin/origin/{origin_id}/edit
  controller: App\Controller\Admin\OriginController::edit
  methods: GET|HEAD|POST
admin.origin.delete:
  path: /admin/origin/{origin_id}/delete
  controller: App\Controller\Admin\OriginController::delete
  methods: GET|HEAD|POST

admin.mock.list.complete:
  path: /admin/mock
  controller: App\Controller\Admin\MockController::all
  methods: GET|HEAD
admin.mock.list:
  path: /admin/origin/{origin_id}/mock
  controller: App\Controller\Admin\MockController::list
  methods: GET|HEAD
admin.mock.list.add:
  path: /admin/mock/add
  controller: App\Controller\Admin\MockController::addWithoutOrigin
  methods: GET|HEAD|POST
admin.mock.add:
  path: /admin/origin/{origin_id}/mock/add
  controller: App\Controller\Admin\MockController::add
  methods: GET|HEAD|POST
admin.mock.edit:
  path: /admin/origin/{origin_id}/mock/{mock_id}/edit
  controller: App\Controller\Admin\MockController::edit
  methods: GET|HEAD|POST
admin.mock.delete:
  path: /admin/origin/{origin_id}/mock/{mock_id}/delete
  controller: App\Controller\Admin\MockController::delete
  methods: GET|HEAD|POST

mock:
  path: /mock/{origin_id}/{url?}
  controller: App\Controller\Mock\MockController::mock
  requirements:
    url: '.+'

proxy:
  path: /proxy/{origin_id}/{url?}
  controller: App\Controller\Proxy\ProxyController::proxy
  requirements:
    url: '.+'
