homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
      path: /admin/origin
      permanent: true

admin.origin.list:
  path: /admin/origin
  controller: App\Controller\Admin\OriginController::list
  methods: GET|HEAD
admin.origin.add:
  path: /admin/origin/add
  controller: App\Controller\Admin\OriginController::add
  methods: GET|HEAD|POST
admin.origin.edit:
  path: /admin/origin/{origin_id}/edit
  controller: App\Controller\Admin\OriginController::edit
  methods: GET|HEAD|POST
admin.origin.delete:
  path: /admin/origin/{origin_id}/delete
  controller: App\Controller\Admin\OriginController::delete
  methods: GET|HEAD|POST

mock:
  path: /mock/{origin_id}/{url?}
  controller: App\Controller\Mock\MockController::mock
  requirements:
    url: '.+'

proxy:
  path: /proxy/{origin_id}/{url?}
  controller: App\Controller\Proxy\ProxyController::proxy
  requirements:
    url: '.+'

proxy.mock:
  path: /proxy-mock/{origin_id}/{url?}
  controller: App\Controller\Proxy\ProxyMockController::proxyMock
  requirements:
    url: '.+'
